// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJQMwtSbguDchb3WlLMuoYP5BhCbH7iYE',
    appId: '1:1031301452202:web:b541a26e0d2eedcea2dbd3',
    messagingSenderId: '1031301452202',
    projectId: 'quanlythietbichothue',
    authDomain: 'quanlythietbichothue.firebaseapp.com',
    storageBucket: 'quanlythietbichothue.firebasestorage.app',
    measurementId: 'G-3SBQ15T3XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWAywZHPH6cypIyUHfEHgTCBxms289uAk',
    appId: '1:1031301452202:android:68887bfd9d2ee930a2dbd3',
    messagingSenderId: '1031301452202',
    projectId: 'quanlythietbichothue',
    storageBucket: 'quanlythietbichothue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd6mnMJW6XeO23rOC0eWvHX-7FKmZaYD0',
    appId: '1:1031301452202:ios:ba81160f6f01f673a2dbd3',
    messagingSenderId: '1031301452202',
    projectId: 'quanlythietbichothue',
    storageBucket: 'quanlythietbichothue.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjectPresentationLastsegment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd6mnMJW6XeO23rOC0eWvHX-7FKmZaYD0',
    appId: '1:1031301452202:ios:ba81160f6f01f673a2dbd3',
    messagingSenderId: '1031301452202',
    projectId: 'quanlythietbichothue',
    storageBucket: 'quanlythietbichothue.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjectPresentationLastsegment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJQMwtSbguDchb3WlLMuoYP5BhCbH7iYE',
    appId: '1:1031301452202:web:eac607bae1afb713a2dbd3',
    messagingSenderId: '1031301452202',
    projectId: 'quanlythietbichothue',
    authDomain: 'quanlythietbichothue.firebaseapp.com',
    storageBucket: 'quanlythietbichothue.firebasestorage.app',
    measurementId: 'G-MQCPLVR02E',
  );
}
